#!/bin/bash

# Qwen3-8B RL training with CISPO (Clipped Importance Sampling Policy Optimization)
# Algorithm: MiniMax-M1 (arxiv:2506.13585)
# Model: Qwen3-8B-Base-sft-dolci-think
# Dataset: Polaris-Dataset (math)
# Backend: Megatron (4 nodes, 32 GPUs)

set -ex

export PYTHONBUFFERED=16

NVLINK_COUNT=$(nvidia-smi topo -m 2>/dev/null | grep -o 'NV[0-9][0-9]*' | wc -l)
if [ "$NVLINK_COUNT" -gt 0 ]; then
    HAS_NVLINK=1
else
    HAS_NVLINK=0
fi
echo "HAS_NVLINK: $HAS_NVLINK (detected $NVLINK_COUNT NVLink references)"

# ---- paths (edit these) ----
PROJECT_DIR=${PROJECT_DIR:-"/jpfs/chenyanxu.9/PeRL/modules/slime"}
MEGATRON_PATH=${MEGATRON_PATH:-"/jpfs/chenyanxu.9/PeRL/modules/Megatron-LM"}
SCRIPT_DIR="${PROJECT_DIR}/scripts"
HF_CKPT="/jpfs-5p/chenyanxu.9/model/Qwen3-8B-Base-sft-dolci-think/iter_0005375-hf"
MEGATRON_CKPT="/jpfs-5p/chenyanxu.9/model/Qwen3-8B-Base-sft-dolci-think/iter_0005375_torch_dist"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
SAVE_DIR="${SAVE_DIR:-/jpfs-5p/chenyanxu.9/model/Qwen3-8B-cispo-rl-${TIMESTAMP}}"
DATA_PATH="/jpfs-5p/qingyu/data/profiling_20260402181029/filtered.jsonl"
LOG_DIR=${SAVE_DIR}/output.log
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
mkdir -p ${SAVE_DIR}

# ---- model architecture (Qwen3-8B) ----
source "${SCRIPT_DIR}/models/qwen3-8B.sh"

# ---- checkpoints ----
CKPT_ARGS=(
   --hf-checkpoint ${HF_CKPT}
   --load ${MEGATRON_CKPT}
   --save ${SAVE_DIR}
   --save-interval 32
)

# ---- rollout & data ----
ROLLOUT_ARGS=(
   --rollout-function-path fully_async_rollout.generate_rollout_fully_async
   --prompt-data ${DATA_PATH}
   --input-key prompt
   --label-key answer
   --apply-chat-template
   --rollout-shuffle
   --balance-data
   --num-rollout 2000
   --rollout-batch-size 64
   --over-sampling-batch-size 90
   --n-samples-per-prompt 8
   --rollout-max-response-len 30000
   --rollout-temperature 1.0
   --global-batch-size 128
   # partial rollout: recycle unfinished samples back to data buffer (useful for 30k long responses)
   --partial-rollout
   # mask off-policy: only train on tokens generated by current policy in partial rollout
   --mask-offpolicy-in-partial-rollout
)

# ---- reward ----
RM_ARGS=(
   --rm-type deepscaler
)

# ---- CISPO algorithm ----
# Key difference from DAPO/GRPO:
#   - Uses custom_loss with CISPO loss function
#   - eps-clip-high is the raw upper bound for IS ratio (e.g. 5.0),
#     NOT the 1+ε offset used in DAPO (which would be 1.28)
#   - CISPO clips IS weights with upper bound only, no lower bound
#   - Clipped IS weights are detached (stop-gradient)
#   - Gradients flow for ALL tokens (no trust-region cutoff)
ALGO_ARGS=(
   --advantage-estimator grpo
   --loss-type custom_loss
   --custom-loss-function-path examples.cispo.cispo_loss.cispo_loss_function
   --kl-coef 0.00
   --entropy-coef 0.00
   # CISPO upper bound for IS ratio (from ScaleRL, arxiv:2510.13786)
   --eps-clip-high 4.0
   # Dynamic sampling: filter prompts where all samples have same reward
   --dynamic-sampling-filter-path slime.rollout.filter_hub.dynamic_sampling_filters.check_reward_nonzero_std
   --use-tis
)

# ---- optimizer (Adam) ----
OPTIMIZER_ARGS=(
   --optimizer adam
   --lr 5e-7
   --lr-decay-style constant
   --weight-decay 0.01
   --adam-beta1 0.9
   --adam-beta2 0.95
   --adam-eps 1e-15
)

# ---- sglang rollout engine ----
SGLANG_ARGS=(
   --rollout-num-gpus-per-engine 1
   --rollout-num-gpus 48
   --sglang-mem-fraction-static 0.85
   --sglang-server-concurrency 256
)

# ---- performance / parallelism ----
PERF_ARGS=(
   --tensor-model-parallel-size 1
   --sequence-parallel
   --pipeline-model-parallel-size 2
   --context-parallel-size 1
   --expert-model-parallel-size 1
   --expert-tensor-parallel-size 1
   --recompute-granularity full
   --recompute-method uniform
   --recompute-num-layers 2
   --use-distributed-optimizer
   --use-dynamic-batch-size
   --max-tokens-per-gpu 30000
)

# ---- misc ----
MISC_ARGS=(
   --actor-num-nodes 2
   --actor-num-gpus-per-node 8
   --attention-dropout 0.0
   --hidden-dropout 0.0
   --accumulate-allreduce-grads-in-fp32
   --attention-softmax-in-fp32
   --attention-backend flash
)
# EVAL_ARGS=(
#    --eval-interval 32
#    --eval-prompt-data aime /jpfs-5p/qingyu/data/aime-2024.jsonl
#    --n-samples-per-eval-prompt 16
#    --eval-max-response-len 30000
#    --eval-top-p 0.95
# )

unset http_proxy
unset https_proxy
unset HTTP_PROXY
unset HTTPS_PROXY
export WANDB_API_KEY=local-b0d90ad40bfaa2dd58fa4525f18c82ccb8aca2c6 # your_wandb_key
export WANDB_ENTITY=automl # your_wandb_entity
wandb login --relogin --host=http://11.71.1.218:8082 ${WANDB_API_KEY}

WANDB_ARGS=(
   --use-wandb
   --wandb-project slime-rl-optim
   --wandb-group adam-cispo-lr-5e-7-beta2-0.98
)


# ---- launch ----
export MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}
export no_proxy="127.0.0.1,${MASTER_ADDR}"

RUNTIME_ENV_JSON="{
  \"env_vars\": {
    \"PYTHONPATH\": \"${MEGATRON_PATH}/:${PROJECT_DIR}/examples/fully_async\",
    \"CUDA_DEVICE_MAX_CONNECTIONS\": \"1\",
    \"NCCL_NVLS_ENABLE\": \"${HAS_NVLINK}\",
    \"WANDB_API_KEY\": \"${WANDB_API_KEY}\",
    \"WANDB_BASE_URL\": \"http://11.71.1.218:8082\",
    \"PYTORCH_CUDA_ALLOC_CONF\": \"expandable_segments:True\"
  }
}"

ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json="${RUNTIME_ENV_JSON}" \
   -- python3 ${PROJECT_DIR}/train_async.py \
   ${EVAL_ARGS[@]} \
   ${MODEL_ARGS[@]} \
   ${CKPT_ARGS[@]} \
   ${ROLLOUT_ARGS[@]} \
   ${RM_ARGS[@]} \
   ${ALGO_ARGS[@]} \
   ${OPTIMIZER_ARGS[@]} \
   ${SGLANG_ARGS[@]} \
   ${PERF_ARGS[@]} \
   ${MISC_ARGS[@]} \
   ${WANDB_ARGS[@]} 2>&1 | tee ${LOG_DIR}
